### ISSUE TITLE
BOM problem

### ISSUE THREAD

**Issue by su-bob** [dprint/dprint-plugin-dockerfile#13]
**Describe the bug**

The dprint no longer handle the BOM problem.
and the version 0.46.x deployed some hours ago. 

https://github.com/dprint/dprint/pull/844

dprint-plugin-dockerfile version: 0.3.0

**Input Code**

```
[BOM]# text file start with BOM 
```

**Expected Output**

```
```

**Actual Output**

```
Message: could not parse Dockerfile:  --> 1:1
```

**Comment by dsherret** [comment]
I opened https://github.com/dprint/dprint-plugin-dockerfile/pull/14
