### ISSUE TITLE
RuntimeError occurs when processing empty comment line

### ISSUE THREAD

**Issue by ganta** [dprint/dprint-plugin-dockerfile#3]
**Describe the bug**

dprint-plugin-dockerfile version: 0.2.2

**Input Code**

```dockerfile
#
```

**Expected Output**

```dockerfile
#
```

**Actual Output**

The following error message is output:
```
Critical error formatting /path/to/Dockerfile. Cannot continue. Message: Originally panicked in dprint-plugin-dockerfile, then failed reinitialize. This may be a bug in the plugin, the dprint cli is out of date, or the plugin is out of date.
Original error: RuntimeError: unreachable
Reinitialize error: RuntimeError: unreachable
Had 1 error(s) formatting.
```

**Comment by dsherret** [comment]
Thanks for reporting this @ganta! If you update to 0.2.3 it should be fixed (run `dprint config update` in the directory with the dprint.json)

**Comment by ganta** [comment]
@dsherret 
Thank you for fixing the issue.
I updated to 0.2.3 and the issue no longer occurs👍🏼
